{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.1.aar",
          "url": "activity-1.3.1.aar",
          "size": 70676,
          "sha512": "f6111bd7f6202f826c4f774d952462f5d4263b693080e66cdebd434262dcd745a090185666944f1832470adc0c4f858ecf90ef0037e93162817c21c2116b1d86",
          "sha256": "6006f41c11e6ea41e7109a70c1db361735b12a9005dd0a6f7c18c3697a9c8b34",
          "sha1": "3f3975748b414c18575bba3568721d1071fd3e0c",
          "md5": "0b54ab9f1555e10cf63a9096a3f1452a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.1.aar",
          "url": "activity-1.3.1.aar",
          "size": 70676,
          "sha512": "f6111bd7f6202f826c4f774d952462f5d4263b693080e66cdebd434262dcd745a090185666944f1832470adc0c4f858ecf90ef0037e93162817c21c2116b1d86",
          "sha256": "6006f41c11e6ea41e7109a70c1db361735b12a9005dd0a6f7c18c3697a9c8b34",
          "sha1": "3f3975748b414c18575bba3568721d1071fd3e0c",
          "md5": "0b54ab9f1555e10cf63a9096a3f1452a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.1-sources.jar",
          "url": "activity-1.3.1-sources.jar",
          "size": 36246,
          "sha512": "78061bf7ade5845cd1788d748f88f1bea4a549dae61dffd671c66779c492bc38c2d8f8cdc0e3db29b78f87d8e32cee40044ff2230b61c2feb189d7d046517efe",
          "sha256": "d7469ea3b7ac2aee586ce36ebc31ab37af10dbb235ddc0b90071190465af251e",
          "sha1": "47b35d483b15e1738de81d26b51ccfc6e2e7b5f8",
          "md5": "a1e27a556fa0408f58894817c3e06d05"
        }
      ]
    }
  ]
}
