{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment-ktx",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.2"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.4.2.aar",
          "url": "navigation-fragment-ktx-2.4.2.aar",
          "size": 1778,
          "sha512": "b40d362756e809c1c27bf64a099b80c68c0f6f1bf733a9c3dcc78132f7870b61f31843240378c36f8a2de1f6c128f129ccc3501327fe1933f61a7290d3fc19cb",
          "sha256": "409b10b6a4bc1ecb2c588d5c33883fd574d5a9c81b05c2f6e27bfa9dd633853a",
          "sha1": "92686721190b3b149c457b0f03456ee43800057e",
          "md5": "46d49c7347cecc4fbc226988c16b951c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.2"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.4.2.aar",
          "url": "navigation-fragment-ktx-2.4.2.aar",
          "size": 1778,
          "sha512": "b40d362756e809c1c27bf64a099b80c68c0f6f1bf733a9c3dcc78132f7870b61f31843240378c36f8a2de1f6c128f129ccc3501327fe1933f61a7290d3fc19cb",
          "sha256": "409b10b6a4bc1ecb2c588d5c33883fd574d5a9c81b05c2f6e27bfa9dd633853a",
          "sha1": "92686721190b3b149c457b0f03456ee43800057e",
          "md5": "46d49c7347cecc4fbc226988c16b951c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-ktx-2.4.2-sources.jar",
          "url": "navigation-fragment-ktx-2.4.2-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
