{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "7.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-7.1.3.jar",
          "url": "aaptcompiler-7.1.3.jar",
          "size": 496987,
          "sha512": "37e3b26913ab78ec9e4889bfcd78dab37faa660c8b98f132b83d6b731c56918bf3d4f11c72b9a587fc5d6a917c8b750f9aadb86e6037bb8006c2e2f1a87e4d3f",
          "sha256": "55bf2da47dbde880169c9bd62930ab028b26e9e7f9d546ba6912aff5702e45c9",
          "sha1": "d04cd89fb9958b3d48c07e70d672ee585c3f58ff",
          "md5": "b74c611da6ff14df942d0c000321c62f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "7.1.3-7984345"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-7.1.3.jar",
          "url": "aaptcompiler-7.1.3.jar",
          "size": 496987,
          "sha512": "37e3b26913ab78ec9e4889bfcd78dab37faa660c8b98f132b83d6b731c56918bf3d4f11c72b9a587fc5d6a917c8b750f9aadb86e6037bb8006c2e2f1a87e4d3f",
          "sha256": "55bf2da47dbde880169c9bd62930ab028b26e9e7f9d546ba6912aff5702e45c9",
          "sha1": "d04cd89fb9958b3d48c07e70d672ee585c3f58ff",
          "md5": "b74c611da6ff14df942d0c000321c62f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-7.1.3-javadoc.jar",
          "url": "aaptcompiler-7.1.3-javadoc.jar",
          "size": 393911,
          "sha512": "0aec103ec76da5aea0c91b903437f29e540569719ed2b1a1cc2a61efbbc8141a1176e477e92d56e1a76dd658b2f56e8a0f367d49091216147eb99efb0f86a5c5",
          "sha256": "31305a4b80eb6bc483d4dcbe8cebbf3a2034f88d4bd6fb4e08cd1f6a61d68287",
          "sha1": "9917a823dced1b762f63cfea95bdf277dbef7de0",
          "md5": "032544d4b47e84e22846bed700f1d68a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-7.1.3-sources.jar",
          "url": "aaptcompiler-7.1.3-sources.jar",
          "size": 152065,
          "sha512": "c307202f609716955ba02ecd5210144943104e4db9c0fca2d70f94ca870515950071bb27e5572688c6ef6d634ed1ead61a0cb806d1441a2b4b1a6e6b8a12cdb9",
          "sha256": "631a0babe5c5fd187073ea90a94256c59c0a64acace49e3a40eaa15f140abb40",
          "sha1": "30383fed460a91110d8638f3f8a5083460fd0b57",
          "md5": "a9b93366d2017c92ddb306b538054eb2"
        }
      ]
    }
  ]
}
