{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.3.1.aar",
          "url": "activity-compose-1.3.1.aar",
          "size": 27600,
          "sha512": "01e0d911f2f106695cd56821e3a239f2592924f7f8aa4224426e136ccb6457252b7f680f6cb938cc48249bfcce69b39368c65f6c06278f91ef21b97d731d2c2b",
          "sha256": "1ca65cbf8948ef3d82dfe70fbf2b2f6805b88dbe7385c67757d601bd5068523c",
          "sha1": "ee19ef5a78c3df728b33455ebb14a8d718409987",
          "md5": "00269ea912b726c6438a8d351837f70f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.3.1.aar",
          "url": "activity-compose-1.3.1.aar",
          "size": 27600,
          "sha512": "01e0d911f2f106695cd56821e3a239f2592924f7f8aa4224426e136ccb6457252b7f680f6cb938cc48249bfcce69b39368c65f6c06278f91ef21b97d731d2c2b",
          "sha256": "1ca65cbf8948ef3d82dfe70fbf2b2f6805b88dbe7385c67757d601bd5068523c",
          "sha1": "ee19ef5a78c3df728b33455ebb14a8d718409987",
          "md5": "00269ea912b726c6438a8d351837f70f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-compose-1.3.1-sources.jar",
          "url": "activity-compose-1.3.1-sources.jar",
          "size": 6677,
          "sha512": "7c2cfbe24b69b4fa424526eb6d5a420770fffcdcb7182e70d024a6ddb222f265c406ebc29caa7ae9a640669c3129a7eb99750c3169e6ac1ee86d6273531c4a0f",
          "sha256": "0c6dd49edddd2ffdc2c3352644b7510d18be6752425b79d1f21505a37ea59190",
          "sha1": "1c7254d3de5b5c2734601aa4b3d52509984b3f75",
          "md5": "33584ea6366f0b3d0100f8ab5bfb49dd"
        }
      ]
    }
  ]
}
