{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7201951"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.1.aar",
          "url": "lifecycle-runtime-testing-2.3.1.aar",
          "size": 7731,
          "sha512": "3e9282cb40353b7fe3e6512de6f652c2299a83b11a4588717c58a8034cce1866bb95a185f117c26c8e6b0eb1cfa21ebf6bcad8bfecdbf86221367a86c37ce3b4",
          "sha256": "a719da2ceaf08ce10d3a3202f696f8b6b87abcf90cdf80b11e2a058b69c44086",
          "sha1": "4f84436e432bd7d494ecadbe809a0bc4e031404e",
          "md5": "67e7241bd2f0ce7ae0776bfbba40b64b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.1.aar",
          "url": "lifecycle-runtime-testing-2.3.1.aar",
          "size": 7731,
          "sha512": "3e9282cb40353b7fe3e6512de6f652c2299a83b11a4588717c58a8034cce1866bb95a185f117c26c8e6b0eb1cfa21ebf6bcad8bfecdbf86221367a86c37ce3b4",
          "sha256": "a719da2ceaf08ce10d3a3202f696f8b6b87abcf90cdf80b11e2a058b69c44086",
          "sha1": "4f84436e432bd7d494ecadbe809a0bc4e031404e",
          "md5": "67e7241bd2f0ce7ae0776bfbba40b64b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.1-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.1-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
