{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.4.2.aar",
          "url": "navigation-ui-2.4.2.aar",
          "size": 95058,
          "sha512": "c69da0a0baa3dd660cc19adfdec695cd9d133694501378e68607328d5d963d7903a06bb12f6622e3e768aea635bf0cb23d9b026f61b489b52be24c1c7fd577e4",
          "sha256": "a82382f1dedd8799b72a33a59d457c8a05fa6ab4a40be70ed1b255db3db4e253",
          "sha1": "3842d5c69ca2444f8b0317ec485dfbbac659b4ca",
          "md5": "f03754e658abd7e87fe51e33ebe5cc58"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.4.2.aar",
          "url": "navigation-ui-2.4.2.aar",
          "size": 95058,
          "sha512": "c69da0a0baa3dd660cc19adfdec695cd9d133694501378e68607328d5d963d7903a06bb12f6622e3e768aea635bf0cb23d9b026f61b489b52be24c1c7fd577e4",
          "sha256": "a82382f1dedd8799b72a33a59d457c8a05fa6ab4a40be70ed1b255db3db4e253",
          "sha1": "3842d5c69ca2444f8b0317ec485dfbbac659b4ca",
          "md5": "f03754e658abd7e87fe51e33ebe5cc58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-2.4.2-sources.jar",
          "url": "navigation-ui-2.4.2-sources.jar",
          "size": 20800,
          "sha512": "6a04f004d3ace555ba21dcfec22dc62dda488516ecf19e2d8e8d4a19f8e8ed43bfbd0857a2a97d4b3221bcf36c38e024ce56630de4debe75bdc531acf2808a0c",
          "sha256": "cf467e3bde7f9bb5b09e3405aa27b4cca09962b3940e65442b3d9075158f4752",
          "sha1": "89d1adbee4f51f0894d7bbd09355ea2dadd307c1",
          "md5": "6ea3eb2e7c238ce796a91a66fa3948bb"
        }
      ]
    }
  ]
}
