{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-coverage-proto",
    "version": "30.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.1.3.jar",
          "url": "android-test-plugin-host-coverage-proto-30.1.3.jar",
          "size": 23204,
          "sha512": "6fc029ad911f173d7a2d5612e400c51b355100efddb102cb06cf9d87d0dbd15375e851ff244bf6c4c0978d16327056426d58f3c3a96475d01334506405351ab8",
          "sha256": "942b13ade6339b765118fd13a8cad05f60b2e749642c3c75666496651d0cd664",
          "sha1": "fe98399ca774e30f9322c4ff53da4824f434d14f",
          "md5": "02108d6643ec7ca754f04af165cc7e46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.1.3.jar",
          "url": "android-test-plugin-host-coverage-proto-30.1.3.jar",
          "size": 23204,
          "sha512": "6fc029ad911f173d7a2d5612e400c51b355100efddb102cb06cf9d87d0dbd15375e851ff244bf6c4c0978d16327056426d58f3c3a96475d01334506405351ab8",
          "sha256": "942b13ade6339b765118fd13a8cad05f60b2e749642c3c75666496651d0cd664",
          "sha1": "fe98399ca774e30f9322c4ff53da4824f434d14f",
          "md5": "02108d6643ec7ca754f04af165cc7e46"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.1.3-javadoc.jar",
          "url": "android-test-plugin-host-coverage-proto-30.1.3-javadoc.jar",
          "size": 425608,
          "sha512": "95c6ae3411e4bee46088edca610181a6c548a14d2faa8076d5dd312b17810595807d3d747fbf89fe6325d18302a33d4e8fec32773febbef86d62f4bd33413cd3",
          "sha256": "e6e3236a3c0886024251309383e710513af7f65964e0fcf970b3ec23bf9ca3f0",
          "sha1": "98ab1bc23b4e2f37f3b954b130332893377be682",
          "md5": "3767bff44a459ac53a97510eb9c1ae13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.1.3-sources.jar",
          "url": "android-test-plugin-host-coverage-proto-30.1.3-sources.jar",
          "size": 11274,
          "sha512": "5424838c941a61e935867cd4c8b5644eaaf20284e4c222efd7d84a691b5f1d27e6af3e31acdda340483e17b17e48e853dc2e35f516b05d92494ccd49c66d2f39",
          "sha256": "737256f09a62cf082c783a63ff92cfd0275047853ccde42ed3ab03c8190775c8",
          "sha1": "712d68df0dc7f3ac4296997ec28503484830e4da",
          "md5": "1a0302ff3015e33221005aa222a8e5c8"
        }
      ]
    }
  ]
}
