{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-ktx",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7101960"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.1.0.aar",
          "url": "savedstate-ktx-1.1.0.aar",
          "size": 1972,
          "sha512": "c364fc26efc0da8a302aa4df53aada3a3d40044c25c7f7ecc4809e0a0ba939fe1fef012714ff0324a1b391bd21f0e64c45ce4f36e97dee4bb7d032e0590e1094",
          "sha256": "e44d61347463b0fafeeb649cbcc3d7109b2eb5e11d1522e986105170cdebbf68",
          "sha1": "8e0bc089d792cc8e6124d4d85b090ba3b199e0ce",
          "md5": "e9fc98038f333a523160c9a2fb6dc59b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.1.0.aar",
          "url": "savedstate-ktx-1.1.0.aar",
          "size": 1972,
          "sha512": "c364fc26efc0da8a302aa4df53aada3a3d40044c25c7f7ecc4809e0a0ba939fe1fef012714ff0324a1b391bd21f0e64c45ce4f36e97dee4bb7d032e0590e1094",
          "sha256": "e44d61347463b0fafeeb649cbcc3d7109b2eb5e11d1522e986105170cdebbf68",
          "sha1": "8e0bc089d792cc8e6124d4d85b090ba3b199e0ce",
          "md5": "e9fc98038f333a523160c9a2fb6dc59b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "savedstate-ktx-1.1.0-sources.jar",
          "url": "savedstate-ktx-1.1.0-sources.jar",
          "size": 1138,
          "sha512": "0e900aadf8c3c8bd044d7dea887dcbe1bff9d359221d0c902320b9af83e453bacd9fabc6cfd5c3fd281e49909c1f168543ec7d997fd012f0537558e586cab8f9",
          "sha256": "c500d54f6588e4630bdef7729c62ca433a7662c93cc0551dfb5c63fad2c970be",
          "sha1": "9292f5a5bc3895f9759d7b6f30291743c1187698",
          "md5": "14f6da869d30af533ad728aed7faba45"
        }
      ]
    }
  ]
}
