{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.4.1.aar",
          "url": "lifecycle-viewmodel-ktx-2.4.1.aar",
          "size": 3955,
          "sha512": "33cc813e7185a324a8e80d6f8e6d9a01a979339f01680a066b184aad4fba57480574d512e0aee6877d5f8a4acaa33a907f1456eb3877c936b647e08cf9963404",
          "sha256": "926e410c92c21d593a08d0d6051a80e1c41627fe493e877f716d0a655c273565",
          "sha1": "822aa4dda6bb55a663d2a37b743c10972bc97f6b",
          "md5": "2679ccee955fc42c78986ed1e3547356"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.4.1.aar",
          "url": "lifecycle-viewmodel-ktx-2.4.1.aar",
          "size": 3955,
          "sha512": "33cc813e7185a324a8e80d6f8e6d9a01a979339f01680a066b184aad4fba57480574d512e0aee6877d5f8a4acaa33a907f1456eb3877c936b647e08cf9963404",
          "sha256": "926e410c92c21d593a08d0d6051a80e1c41627fe493e877f716d0a655c273565",
          "sha1": "822aa4dda6bb55a663d2a37b743c10972bc97f6b",
          "md5": "2679ccee955fc42c78986ed1e3547356"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.4.1-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.4.1-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}
