{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7104547"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.3.0.aar",
          "url": "lifecycle-viewmodel-ktx-2.3.0.aar",
          "size": 6328,
          "sha512": "d09d7000ee82050cdfba43e978a8b367b47f558cf77cc5551bd5b952fb49d69909b5b338bac469d5fab33d9c371a416398ff540a32b6cea0f74863f0ccaa229c",
          "sha256": "f090855f714d8849ac3581169bfe765f1584df38e53cbf11afebd72cb53d9172",
          "sha1": "b602d0b1f3ccd9276b7cd5a1513856dccb962735",
          "md5": "804e5aea743f025e606ad8528b49a239"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.3.0.aar",
          "url": "lifecycle-viewmodel-ktx-2.3.0.aar",
          "size": 6328,
          "sha512": "d09d7000ee82050cdfba43e978a8b367b47f558cf77cc5551bd5b952fb49d69909b5b338bac469d5fab33d9c371a416398ff540a32b6cea0f74863f0ccaa229c",
          "sha256": "f090855f714d8849ac3581169bfe765f1584df38e53cbf11afebd72cb53d9172",
          "sha1": "b602d0b1f3ccd9276b7cd5a1513856dccb962735",
          "md5": "804e5aea743f025e606ad8528b49a239"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.3.0-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.3.0-sources.jar",
          "size": 3228,
          "sha512": "846c73103262a8b30af9a89edbe0c2aea442b2ab868244f2c9cac5b3c0adada37de5c3e251cc1ac70995d83f4c25b0ddefcd7fe3766ed31fd70b601179725573",
          "sha256": "ffff56d094557958b5fecaf8100957cbf027bf5f6933cff7106653617ab18fc1",
          "sha1": "5039b0b0dd04a2496c1bbbddc897c5dfa6b8ed43",
          "md5": "5783315fbbc686a340433ed10bbfa0b4"
        }
      ]
    }
  ]
}
