{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.libraries.mapsplatform.secrets-gradle-plugin",
    "module": "secrets-gradle-plugin",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "secrets-gradle-plugin-2.0.1.jar",
          "url": "secrets-gradle-plugin-2.0.1.jar",
          "size": 13867,
          "sha512": "beb5b93dd15dcd2b182f89dccdc4871bd85b9b68b9e1a8ee74ee092582a680b2d454843f710813b3a52fd46a8cd485648fdf892e1c60d428300760ddfa89aa3d",
          "sha256": "9f3170d9a77364dd0358595ab6a5a3bed31012052ee46c768535a4fff1234ca2",
          "sha1": "5cce19cffff3bcc4f5941f76b0593e763f525ba3",
          "md5": "800dee0d198d876cb304a21e559a7ade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "secrets-gradle-plugin-2.0.1.jar",
          "url": "secrets-gradle-plugin-2.0.1.jar",
          "size": 13867,
          "sha512": "beb5b93dd15dcd2b182f89dccdc4871bd85b9b68b9e1a8ee74ee092582a680b2d454843f710813b3a52fd46a8cd485648fdf892e1c60d428300760ddfa89aa3d",
          "sha256": "9f3170d9a77364dd0358595ab6a5a3bed31012052ee46c768535a4fff1234ca2",
          "sha1": "5cce19cffff3bcc4f5941f76b0593e763f525ba3",
          "md5": "800dee0d198d876cb304a21e559a7ade"
        }
      ]
    }
  ]
}
