{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-retention-proto",
    "version": "30.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.3.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.3.jar",
          "size": 39328,
          "sha512": "40c8defe01da1ed41aa651741829145a28b48ae9fb8b14c4df9b0ee558e54858db30f922ead63e281ad038084db36f4ef0750fd87a409e2197987b853961cc0a",
          "sha256": "5d361fa55b3c4e2416f43c0bb08aca894e888e8e8b8315f526ff00803c208159",
          "sha1": "0bd76fcd10c4cd3211dd63d6a18fcde9a4ddd2a7",
          "md5": "2ad8eb77c92c9cfc2542b39247f80553"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.3.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.3.jar",
          "size": 39328,
          "sha512": "40c8defe01da1ed41aa651741829145a28b48ae9fb8b14c4df9b0ee558e54858db30f922ead63e281ad038084db36f4ef0750fd87a409e2197987b853961cc0a",
          "sha256": "5d361fa55b3c4e2416f43c0bb08aca894e888e8e8b8315f526ff00803c208159",
          "sha1": "0bd76fcd10c4cd3211dd63d6a18fcde9a4ddd2a7",
          "md5": "2ad8eb77c92c9cfc2542b39247f80553"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.3-javadoc.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.3-javadoc.jar",
          "size": 451215,
          "sha512": "b286e2665c114ce129f6a44fd2eea9e180232452daff420e952429b2795e24b12a096027bf8d7647718312163205a54d23f60098f7cb0f0635dcf3675736ffbe",
          "sha256": "d1d162e3763ee7901138e00bfd37244a8bddb147c33ae4c8269db3ba7226b9ca",
          "sha1": "67a045814f36b03e15b059dd23f75e14881b6aa9",
          "md5": "112bf22a63406de20771044fdc0138f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.3-sources.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.3-sources.jar",
          "size": 16525,
          "sha512": "38181893fbcae32487dcdc92c1f3826dae819f07bd7b0f5b98f76ca94c7d77dba07a625c99823beb1882c6999508348bc8c3f984b6ac1796d50af96e0867b603",
          "sha256": "aee687de08ec7267b849026bf24f1e24010e859f886fe66f8d50ad85615384d4",
          "sha1": "5b40cdb0a229cb6b170251d44d38588a4e3fdd30",
          "md5": "3bb5b18a5049dc3c4a1e87a27bb6d1b4"
        }
      ]
    }
  ]
}
