{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "30.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-30.1.3.jar",
          "url": "manifest-merger-30.1.3.jar",
          "size": 208014,
          "sha512": "2082c75f50674de42616a7ff95fceef7a3a0a666e8ad3c9c0af6844499fea856cba0a5fafbd8b12803a7cbe1e6091c9ed80e88a7d1ac3a2e67f5f5b4777b92f1",
          "sha256": "fb04445bd588ccd27dacd5e139abed42246f55e6785eebf66659857233207fac",
          "sha1": "c04a43df33114bf207631d23d96c069070a46101",
          "md5": "0434256fe338b007c8ebf1bb73b691b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-30.1.3.jar",
          "url": "manifest-merger-30.1.3.jar",
          "size": 208014,
          "sha512": "2082c75f50674de42616a7ff95fceef7a3a0a666e8ad3c9c0af6844499fea856cba0a5fafbd8b12803a7cbe1e6091c9ed80e88a7d1ac3a2e67f5f5b4777b92f1",
          "sha256": "fb04445bd588ccd27dacd5e139abed42246f55e6785eebf66659857233207fac",
          "sha1": "c04a43df33114bf207631d23d96c069070a46101",
          "md5": "0434256fe338b007c8ebf1bb73b691b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-30.1.3-javadoc.jar",
          "url": "manifest-merger-30.1.3-javadoc.jar",
          "size": 580404,
          "sha512": "a360a16789d9695d71918c9bb1b49e547102cc6d6bcba7fc3ab7f55f67daa81b482a09130345bf09cc4f149333f09e1a624df8485b82f21e62f52a0aa829d4d4",
          "sha256": "c424747a869078213b7d010b7da51cd2d95b8446672da0bf6e436bc3ccf51fd5",
          "sha1": "ba5d9f672559bfc7bf61c74db9b0adc7b8e7a27d",
          "md5": "2697bc29cdb30a0b2ce46ef5c78a6c3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-30.1.3-sources.jar",
          "url": "manifest-merger-30.1.3-sources.jar",
          "size": 210197,
          "sha512": "23cf03602e3899290f7c8a29ba400f4ad435f785fa144ab647f2ec143597241ef67d719a59b434b4710742e3d870bc4b9e33f1a90f6df85a75cf252b28b502e2",
          "sha256": "33ed570c5aec35c8fcaf3b6f2a25913c86935b48eba54199703df85b87efa276",
          "sha1": "7ebcc37c7875ce1d649d9faa21fe6f87e69da3bc",
          "md5": "24add43e77e2a7d695d5a448ac732405"
        }
      ]
    }
  ]
}
