{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "protos",
    "version": "30.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "protos-30.1.3.jar",
          "url": "protos-30.1.3.jar",
          "size": 5183836,
          "sha512": "89c7f03c0159749324d992a26f365c245d677a806712e232c8a8d6ceb10ebf5a89f513d0e565f64725eb25691c9b9c191be4d9c8892cc77588300f794cd1f10a",
          "sha256": "6c7c2fc5ea590797db1532d7879b717cdd6328c8f74c0e32ddccdf392e94ffe6",
          "sha1": "4024a2955700076fde303e14ea0557baaee8f9ba",
          "md5": "a9e6c53d4693f5132d63719b1f43b010"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "protos-30.1.3.jar",
          "url": "protos-30.1.3.jar",
          "size": 5183836,
          "sha512": "89c7f03c0159749324d992a26f365c245d677a806712e232c8a8d6ceb10ebf5a89f513d0e565f64725eb25691c9b9c191be4d9c8892cc77588300f794cd1f10a",
          "sha256": "6c7c2fc5ea590797db1532d7879b717cdd6328c8f74c0e32ddccdf392e94ffe6",
          "sha1": "4024a2955700076fde303e14ea0557baaee8f9ba",
          "md5": "a9e6c53d4693f5132d63719b1f43b010"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protos-30.1.3-javadoc.jar",
          "url": "protos-30.1.3-javadoc.jar",
          "size": 8849125,
          "sha512": "fa98fbf0a9306b6215394b57f4f6afaff03c7b17494079b4b919e455f5bb394d45ef2c140398cfd67096fdad66d71065f21e52687288ecbd8c70fa60f6915c12",
          "sha256": "29d8745fcc5a43ea9b2552c8891a6b544c2632855f533d61f2355ed555955a0c",
          "sha1": "a4969462f350a7cd34cb17cb5fa1d37bfa7602d0",
          "md5": "f18d3a87a694f52f30f2def9f78fd2bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protos-30.1.3-sources.jar",
          "url": "protos-30.1.3-sources.jar",
          "size": 2141174,
          "sha512": "6d856b1bafb198afbf2d265cf0e799f1c66e41b5249de20e1e52f29a38ccea964f3015b95c1664c6d4555789dd9785c2c2a3ca3e674981571181835df687bf6d",
          "sha256": "6dfdb2b695974e51f06b0aab19d6b8f6661465aa4ec553b6bd18ba80d2cf26b0",
          "sha1": "4f707160feee37b126ac987c556faad4a7c30743",
          "md5": "c4f4461a9324634c529a0f2e2349e78a"
        }
      ]
    }
  ]
}
