{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "sdk-common",
    "version": "30.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sdk-common-30.1.3.jar",
          "url": "sdk-common-30.1.3.jar",
          "size": 1419720,
          "sha512": "1683c6fd7795952ce3dda77f6214e1e3d42aadaf66928898b54f81bbb1e6faac1f55d49f55d203bff311ec0d6faef23aecffc946eb94639d254d38c7c7d9b953",
          "sha256": "6c44d6ffa3b1b34505fcb05422f08bd293391648dc974cc252ddc541fd9b27f5",
          "sha1": "b71649b45e4ad86c9f7fbcde4c00c8d1a877884f",
          "md5": "f8db5910a0b2d25238385e9a9c994a43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.intellij.deps",
          "module": "trove4j",
          "version": {
            "requires": "1.0.20181211"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "7.0.0-beta04-7396180"
          }
        },
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-common-30.1.3.jar",
          "url": "sdk-common-30.1.3.jar",
          "size": 1419720,
          "sha512": "1683c6fd7795952ce3dda77f6214e1e3d42aadaf66928898b54f81bbb1e6faac1f55d49f55d203bff311ec0d6faef23aecffc946eb94639d254d38c7c7d9b953",
          "sha256": "6c44d6ffa3b1b34505fcb05422f08bd293391648dc974cc252ddc541fd9b27f5",
          "sha1": "b71649b45e4ad86c9f7fbcde4c00c8d1a877884f",
          "md5": "f8db5910a0b2d25238385e9a9c994a43"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-common-30.1.3-javadoc.jar",
          "url": "sdk-common-30.1.3-javadoc.jar",
          "size": 1645538,
          "sha512": "a87367900de1deed419817ce236958070f7471b5d937b96dc2deb368c5be428ab9cb99df48b9b666e7518e3ad84ebcc4f0a8edccea2cc7b3c36e954d01c6dd27",
          "sha256": "415dba47305e8dc07d700fee2c25fbec4e4c7b76662f8da52b51065028b2cd3b",
          "sha1": "71414078bc2693e13d080a2d2858ec78147ba9bc",
          "md5": "0939e03397009ff30565cefe19012839"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-common-30.1.3-sources.jar",
          "url": "sdk-common-30.1.3-sources.jar",
          "size": 804690,
          "sha512": "8c6071392dac193b2e1a8defc1f3a538b7336537ac5a5a55f13a19c559968bd16d8b085dbbfaf043dde3a5a77d8ba8f3bc640fb4e6a125eba8091097e5f2e1ed",
          "sha256": "a464f56fb546b4e0461a25bc204dcbccf42adb29ef53bd6d41ae4b58a27e3be5",
          "sha1": "c879b8482faa3d20df6696bc22a26b78bd8260f2",
          "md5": "f69bc8cd17a633fcbfe19f03ee69c58c"
        }
      ]
    }
  ]
}
