{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "7.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.1.3.jar",
          "url": "gradle-api-7.1.3.jar",
          "size": 234302,
          "sha512": "9c0fa99a3294fa0cc4d69f9daa8ed8a6c3b6b07546eff79f3b4aebae740b60411e3669716894d9390fa013dabce657fc25cff462518849395a2b1964b7898795",
          "sha256": "483726f1f0bd2b07b521de32cacc22954b9490ebc158efca59a7c8ddee4d0331",
          "sha1": "c546e42bcd8a6cc21832bb597608e220ab4afd9c",
          "md5": "6ecf3b36308d24af15c02d1f0008d835"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.1.3.jar",
          "url": "gradle-api-7.1.3.jar",
          "size": 234302,
          "sha512": "9c0fa99a3294fa0cc4d69f9daa8ed8a6c3b6b07546eff79f3b4aebae740b60411e3669716894d9390fa013dabce657fc25cff462518849395a2b1964b7898795",
          "sha256": "483726f1f0bd2b07b521de32cacc22954b9490ebc158efca59a7c8ddee4d0331",
          "sha1": "c546e42bcd8a6cc21832bb597608e220ab4afd9c",
          "md5": "6ecf3b36308d24af15c02d1f0008d835"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.1.3-javadoc.jar",
          "url": "gradle-api-7.1.3-javadoc.jar",
          "size": 464816,
          "sha512": "08dff810c40b9ced1cb4d2340d770295d11fb346a9216720b391a057e7712d1717b5d8efd9525a5f334ed7851c631e0f4152a63c3ae4394a127dbf259cb002d3",
          "sha256": "8da800cd6796bae93765ad8021b9b6759cd687a8f928131dac798684aa72f591",
          "sha1": "bcc1f92410d825e15a5058014f00a3a827b832a3",
          "md5": "b9befd65e7e50452b47fc51cfed4f040"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.1.3-sources.jar",
          "url": "gradle-api-7.1.3-sources.jar",
          "size": 235690,
          "sha512": "a9079a92d459829bce315d06b2cbc5b47736d8aaa78b639c5d66875b2bb21740cdcb0821301d2e9aa554602e414f11c6dc03701e8b1479bc7503b45d9693fb67",
          "sha256": "4f250cd471a44fe3eec74d970b4ad241f956c68ccd8e7952eeebb9ef7754ab64",
          "sha1": "61ef393b68f4f000ee02f4e406512c8043027d44",
          "md5": "e350495105927d8a1c8ba15450f9c624"
        }
      ]
    }
  ]
}
