{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.2"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.2.aar",
          "url": "navigation-ui-ktx-2.4.2.aar",
          "size": 1768,
          "sha512": "08eafe082105d90c07fbf6aba1b6c9f50e169b864ca1fc0ae7d781d138c2ec39ba395cad891f5170301cd52079da3b7166359b1e0dcf263dd6779d125ba3c359",
          "sha256": "d9af9a15b7466914f70bcf8342584cc25071db2a9ed9577824453226df9cd60d",
          "sha1": "ff6a80c1572efc92b173b4c1d39711ca52a36d1e",
          "md5": "d24dfaaf54cab424bfcf2f1c9ab61b0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.2"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.2.aar",
          "url": "navigation-ui-ktx-2.4.2.aar",
          "size": 1768,
          "sha512": "08eafe082105d90c07fbf6aba1b6c9f50e169b864ca1fc0ae7d781d138c2ec39ba395cad891f5170301cd52079da3b7166359b1e0dcf263dd6779d125ba3c359",
          "sha256": "d9af9a15b7466914f70bcf8342584cc25071db2a9ed9577824453226df9cd60d",
          "sha1": "ff6a80c1572efc92b173b4c1d39711ca52a36d1e",
          "md5": "d24dfaaf54cab424bfcf2f1c9ab61b0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.2-sources.jar",
          "url": "navigation-ui-ktx-2.4.2-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
