{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.4.2.aar",
          "url": "navigation-compose-2.4.2.aar",
          "size": 1083488,
          "sha512": "72cc8f7ceaba16c2fd6b755b152fcf8e8d3b991413b235204b5df283e922bfb3f57f5fcd5b570fe5e245a6ed9be40a4b79e8b0e2fc6cec8983641187c770e8f8",
          "sha256": "4b353dd4546a26e592a3196db750560631498045a19ab351767b3e6138974c36",
          "sha1": "7a88faaeeec8256a993e85f80808324a9b450040",
          "md5": "8274379aaaf2f076d4d475b373e31994"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.4.2.aar",
          "url": "navigation-compose-2.4.2.aar",
          "size": 1083488,
          "sha512": "72cc8f7ceaba16c2fd6b755b152fcf8e8d3b991413b235204b5df283e922bfb3f57f5fcd5b570fe5e245a6ed9be40a4b79e8b0e2fc6cec8983641187c770e8f8",
          "sha256": "4b353dd4546a26e592a3196db750560631498045a19ab351767b3e6138974c36",
          "sha1": "7a88faaeeec8256a993e85f80808324a9b450040",
          "md5": "8274379aaaf2f076d4d475b373e31994"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-compose-2.4.2-sources.jar",
          "url": "navigation-compose-2.4.2-sources.jar",
          "size": 10928,
          "sha512": "5869f2894d7732bb8d7b402d0e60e76b915d32227965a248c0848cc31ea6a574bee5854599ba4b98fd337e36b61da0d46eeaf06e611d3c617185720699b7c358",
          "sha256": "ca9f6cdc12a8b4d3811c7f242fd5f19439ffeb01dd3209e815a20fa695850886",
          "sha1": "62becddcad66de8aa78af1f5872dc8a3d6ee8526",
          "md5": "ce836fad6d37653f18ab5b41c53e0ea1"
        }
      ]
    }
  ]
}
