{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.4.2.aar",
          "url": "navigation-common-ktx-2.4.2.aar",
          "size": 1771,
          "sha512": "e2f2643a7b2393028447d3d67199137db49870cbaf5f73b916ac4178590f3d30163fac5b2be2edeca092970959dca2dd719525f9abbacb9e3c1dca913f1c53a9",
          "sha256": "2b0e6d5ef46f790abcbf124532b44434d4866dd425a6dfeca406f572dfeb039d",
          "sha1": "bf38e93a94e87096f21d78844045c2970ca42b98",
          "md5": "1bc08a2adcf0de7e4f7468b73816d3c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.4.2.aar",
          "url": "navigation-common-ktx-2.4.2.aar",
          "size": 1771,
          "sha512": "e2f2643a7b2393028447d3d67199137db49870cbaf5f73b916ac4178590f3d30163fac5b2be2edeca092970959dca2dd719525f9abbacb9e3c1dca913f1c53a9",
          "sha256": "2b0e6d5ef46f790abcbf124532b44434d4866dd425a6dfeca406f572dfeb039d",
          "sha1": "bf38e93a94e87096f21d78844045c2970ca42b98",
          "md5": "1bc08a2adcf0de7e4f7468b73816d3c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.4.2-sources.jar",
          "url": "navigation-common-ktx-2.4.2-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
