{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vmadalin",
    "module": "easypermissions-ktx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ixcbdhrywrdanjzjcuilrm6sdy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "easypermissions-ktx-1.0.0.aar",
          "url": "easypermissions-ktx-1.0.0.aar",
          "size": 43151,
          "sha512": "f02015b78bd08ec8f9264a8484c4df008c3c24025002dde666c1fcbee7b239a86a7d2db545a4b42f0789597402dc45d9f72a1908179b62dc6e3bcdb979b7fd83",
          "sha256": "b4b0edfb73e8a38dc711fffb060ddafd7fc9d47c3c202721cbd3da3ccedaf1e5",
          "sha1": "d8eafce0820e8a4b04d0aa6e53bf6b8c05353498",
          "md5": "bfd4301f8daa20242fad08a67ad1e3af"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "easypermissions-ktx-1.0.0.aar",
          "url": "easypermissions-ktx-1.0.0.aar",
          "size": 43151,
          "sha512": "f02015b78bd08ec8f9264a8484c4df008c3c24025002dde666c1fcbee7b239a86a7d2db545a4b42f0789597402dc45d9f72a1908179b62dc6e3bcdb979b7fd83",
          "sha256": "b4b0edfb73e8a38dc711fffb060ddafd7fc9d47c3c202721cbd3da3ccedaf1e5",
          "sha1": "d8eafce0820e8a4b04d0aa6e53bf6b8c05353498",
          "md5": "bfd4301f8daa20242fad08a67ad1e3af"
        }
      ]
    }
  ]
}
