# Generated by Django 3.2.3 on 2022-04-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_hour', models.TextField()),
                ('two_hours', models.TextField()),
                ('three_hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.IntegerField()),
                ('commission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
                ('job_name', models.TextField()),
                ('hire_date', models.DateField()),
                ('status', models.CharField(max_length=4)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapi.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapi.location')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapi.salary')),
            ],
        ),
    ]
