# Generated by Django 3.2.3 on 2022-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0002_auto_20220425_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='one_hour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='three_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='two_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
