{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.1.aar",
          "url": "activity-ktx-1.3.1.aar",
          "size": 30061,
          "sha512": "fc8e665d99786c94c0f87cb4a3d8bfd42e9ab2b2ac9ab4a07a5e881a6b2c5b63416f831af5f7f59323fd34e5d65999313eb717303898cf648a40e0d3c35d413d",
          "sha256": "9adc905de021afe039e4107a49c0bead35661c69a8a8086af448d01ecd5d6130",
          "sha1": "da86b5c5686bc8651dec55827f9984406ce51a06",
          "md5": "6d5da5a1fa5157a6c5a4cf1a638dab13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.1.aar",
          "url": "activity-ktx-1.3.1.aar",
          "size": 30061,
          "sha512": "fc8e665d99786c94c0f87cb4a3d8bfd42e9ab2b2ac9ab4a07a5e881a6b2c5b63416f831af5f7f59323fd34e5d65999313eb717303898cf648a40e0d3c35d413d",
          "sha256": "9adc905de021afe039e4107a49c0bead35661c69a8a8086af448d01ecd5d6130",
          "sha1": "da86b5c5686bc8651dec55827f9984406ce51a06",
          "md5": "6d5da5a1fa5157a6c5a4cf1a638dab13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.3.1-sources.jar",
          "url": "activity-ktx-1.3.1-sources.jar",
          "size": 7769,
          "sha512": "804afefb365825fba128fb90e94e2a52c592f086d4829c379113a6dff9541f59fba14d174ed54808d3d218fa67d8c7b0d13b46fbf21d5fa37289f20712888cf2",
          "sha256": "e9203b000c2790d6f867dd642380f820cf97ba9a821e96daadac8b7dba19e0b3",
          "sha1": "370e20946dad67d9ce26dbe3f33034ddf84600c4",
          "md5": "eafcc6f70cc644f6a4d16ba2482a3c1b"
        }
      ]
    }
  ]
}
