{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "shared",
    "version": "30.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "shared-30.0.4.jar",
          "url": "shared-30.0.4.jar",
          "size": 110476,
          "sha512": "f97f86be0606953653c36a3f15eb7040103c5b97b261e1718d0d78a57ae2ff9814b8616d1e99cd687216336af5a40d494ddd65fabfeea71e6813b56249e6bad5",
          "sha256": "91cada37f5035b5d313cce64fde2a3c3a3f58b267edb80b0e3e94372e3bcf2d1",
          "sha1": "d02bc8a370cf76be821686ac47afc4621951535c",
          "md5": "805d8764e51004fe18fffa6db05c8f74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.0.4"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "shared-30.0.4.jar",
          "url": "shared-30.0.4.jar",
          "size": 110476,
          "sha512": "f97f86be0606953653c36a3f15eb7040103c5b97b261e1718d0d78a57ae2ff9814b8616d1e99cd687216336af5a40d494ddd65fabfeea71e6813b56249e6bad5",
          "sha256": "91cada37f5035b5d313cce64fde2a3c3a3f58b267edb80b0e3e94372e3bcf2d1",
          "sha1": "d02bc8a370cf76be821686ac47afc4621951535c",
          "md5": "805d8764e51004fe18fffa6db05c8f74"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared-30.0.4-javadoc.jar",
          "url": "shared-30.0.4-javadoc.jar",
          "size": 261,
          "sha512": "2b70db93f290d9528e37aa0e7778cdfb392d438f12d6ed8ed3d19d5b758c59faf8175537f33090a07a400beef950f4c238a46d17aec8006cfc9a460551bc3102",
          "sha256": "9335c4c8a52a5b43dd9603a29d36fbb1c3f3aa3a0b0f36abb9dd213182180808",
          "sha1": "bb54c6f1cbf3b26f7b407abd9ca95cbb6314399f",
          "md5": "0c56c317e05511178d1d8576e0c985cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared-30.0.4-sources.jar",
          "url": "shared-30.0.4-sources.jar",
          "size": 22294,
          "sha512": "3f0e164908017af37ebeb15f7e1690c36401442a3704cb6940a0d4ea4ca5856800691ca63dfeac383457001a93713b98543d16a545478485911049298b59512d",
          "sha256": "d76aeb80546b593f55eef1431b07143d852ce38a5140f9a5cd79028f60bd7ff9",
          "sha1": "be6968a3e77598fbc9822200c089bdd0ca4f79f3",
          "md5": "8b79c279f46bb0a765b017986001613b"
        }
      ]
    }
  ]
}
