{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.1.aar",
          "url": "lifecycle-livedata-2.4.1.aar",
          "size": 10998,
          "sha512": "f8ef0142acdf93c444c68bea065646753f12512197e8c0ca13887a8857d59ea12204401b41ea4c96552d1b948b0f5e24bc76807ba6aff311971ae76b02196b2b",
          "sha256": "78d04726be73a905870dafed01e107b350f84b38258c8f6a12acd310393e68ea",
          "sha1": "8f88c30c3588d0613a7d6798f980e1d3e651245e",
          "md5": "46fc9d27059c5c8476cc1e682270c6b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.1.aar",
          "url": "lifecycle-livedata-2.4.1.aar",
          "size": 10998,
          "sha512": "f8ef0142acdf93c444c68bea065646753f12512197e8c0ca13887a8857d59ea12204401b41ea4c96552d1b948b0f5e24bc76807ba6aff311971ae76b02196b2b",
          "sha256": "78d04726be73a905870dafed01e107b350f84b38258c8f6a12acd310393e68ea",
          "sha1": "8f88c30c3588d0613a7d6798f980e1d3e651245e",
          "md5": "46fc9d27059c5c8476cc1e682270c6b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.4.1-sources.jar",
          "url": "lifecycle-livedata-2.4.1-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
