{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "sdklib",
    "version": "30.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "30.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdklib-30.1.3.jar",
          "url": "sdklib-30.1.3.jar",
          "size": 690434,
          "sha512": "dd3d1adb8ef8fc83e65f1a8e52b2bb080dc94d66d0a90ca0575f65e3e18b6ef5525c24c2a97df8889e6dfe3394f3acad4210887a5c1c9b4803480ebf5aebeac8",
          "sha256": "edf456a67ada3154c9fd23f9829699e8b654dc7f33f2430b50839d6904760b48",
          "sha1": "9b211420a27e1d5924fadc0fccea3f54ee65fdfd",
          "md5": "4b5b6f8af99bbfa3aad4a5c1c47f2f65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "dvlib",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.20"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "30.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdklib-30.1.3.jar",
          "url": "sdklib-30.1.3.jar",
          "size": 690434,
          "sha512": "dd3d1adb8ef8fc83e65f1a8e52b2bb080dc94d66d0a90ca0575f65e3e18b6ef5525c24c2a97df8889e6dfe3394f3acad4210887a5c1c9b4803480ebf5aebeac8",
          "sha256": "edf456a67ada3154c9fd23f9829699e8b654dc7f33f2430b50839d6904760b48",
          "sha1": "9b211420a27e1d5924fadc0fccea3f54ee65fdfd",
          "md5": "4b5b6f8af99bbfa3aad4a5c1c47f2f65"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdklib-30.1.3-javadoc.jar",
          "url": "sdklib-30.1.3-javadoc.jar",
          "size": 1177589,
          "sha512": "2a9a2045eb748b5a7be1b6af011a6ec7ce5dfb26ba68e45e63bd3967f87064b16d26e3f9f4f9049391adbd819df9fcbb7cbe83972567e7885c78ccdefb2214c9",
          "sha256": "bfdcc37da23515b19b23b9af6dcd45d85ff0d21b4a8d4525585dd4a16c9a213d",
          "sha1": "ee46b7ba29da8d731d26779f85ab2d6e637c5379",
          "md5": "33a2cae28071f9467f4fc92a4d641af7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdklib-30.1.3-sources.jar",
          "url": "sdklib-30.1.3-sources.jar",
          "size": 577807,
          "sha512": "dbf1552f3eccf989c174b8eb8c2426923818fd712c2bb27dfbe8082352e7897385b6028cba31c19ce0764f96197bdd3eaecdc5ae2f216568296af165dd2acfa5",
          "sha256": "4de1dc9cc3776e4783d9d2855360eb661772d06548187dad2372410bd3d34078",
          "sha1": "4f516d08a9607f8aa3b6ac4954303834bfea8699",
          "md5": "3dcfc5b922b5ca5ba6bd2ed91a00eca7"
        }
      ]
    }
  ]
}
