{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-ktx",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.4.1.aar",
          "url": "fragment-ktx-1.4.1.aar",
          "size": 14680,
          "sha512": "8884f3a41d5092999fe3ab2831b3e1c42dd49289cc807ddfd8baf72ee0f79c094a8f85cdc936362dad478aa159b8879eedc73c5018b42406512335f1e218498e",
          "sha256": "cbcd696a528b0e3a2ea11e0624e418c23cccd73cd5cd9f6fe272a3bb92eb91eb",
          "sha1": "599e763ee251b692f0decc0439ef3010236dc85b",
          "md5": "89baa4e2b70ec7639074ac644a6163cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.4.1.aar",
          "url": "fragment-ktx-1.4.1.aar",
          "size": 14680,
          "sha512": "8884f3a41d5092999fe3ab2831b3e1c42dd49289cc807ddfd8baf72ee0f79c094a8f85cdc936362dad478aa159b8879eedc73c5018b42406512335f1e218498e",
          "sha256": "cbcd696a528b0e3a2ea11e0624e418c23cccd73cd5cd9f6fe272a3bb92eb91eb",
          "sha1": "599e763ee251b692f0decc0439ef3010236dc85b",
          "md5": "89baa4e2b70ec7639074ac644a6163cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-ktx-1.4.1-sources.jar",
          "url": "fragment-ktx-1.4.1-sources.jar",
          "size": 6123,
          "sha512": "d104a5c4e1cf585e573e45de9e5a497cb209f8e0cf0fb50f3992d33ea0bfeedabc2a6d608bab7e8b836d33c8fa5b0404dd612e0e9ff298e5354c26e09059b89e",
          "sha256": "429b8f4cbdefe04bfec17fad5866139979b43ef760d39fe3717930c4a9653337",
          "sha1": "4e12207413e48643ad83b250e97550d291c58598",
          "md5": "95ed66abef9d5dd75be32357336c236b"
        }
      ]
    }
  ]
}
