{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.1.aar",
          "url": "lifecycle-service-2.4.1.aar",
          "size": 4298,
          "sha512": "89b9ec5cf56991abd961c4ab6c8afa9709b27649912a1f426f4c9d6de2ea86b04bc9aa8b3a24955f5d4259caa0e921e46f0a4b60a3aaff3c4e5937ae32b47157",
          "sha256": "82df0c2d785db5a6921eef6e3bb9e22a9d8e6fcb2f82681c3aa50348f979e804",
          "sha1": "302e7ebf127b884e251e745143e601a3c695eead",
          "md5": "75afe817269ef57a7265320d3fc80709"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.1.aar",
          "url": "lifecycle-service-2.4.1.aar",
          "size": 4298,
          "sha512": "89b9ec5cf56991abd961c4ab6c8afa9709b27649912a1f426f4c9d6de2ea86b04bc9aa8b3a24955f5d4259caa0e921e46f0a4b60a3aaff3c4e5937ae32b47157",
          "sha256": "82df0c2d785db5a6921eef6e3bb9e22a9d8e6fcb2f82681c3aa50348f979e804",
          "sha1": "302e7ebf127b884e251e745143e601a3c695eead",
          "md5": "75afe817269ef57a7265320d3fc80709"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.4.1-sources.jar",
          "url": "lifecycle-service-2.4.1-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
