# Generated by Django 3.2.3 on 2022-05-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offsite',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='onsite',
            name='emp_id',
        ),
    ]
