# Generated by Django 3.2.3 on 2022-04-26 08:26

from django.db import migrations, models
import trackapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0004_alter_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to=trackapi.models.employee_directory_path),
        ),
    ]
