{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.2.aar",
          "url": "navigation-runtime-2.4.2.aar",
          "size": 117238,
          "sha512": "f162d61675b6eaeeddf86f8bd7e0fdff49501537be39aa142986f41ad80720f10bdb3b24f8a9b2ddba0948874492876348213cd109748f442d9a147ac53b5ac8",
          "sha256": "ae8a1bce56e5df56e6512103c3d0608edbd1d48cc409649b12f482469eec3fbe",
          "sha1": "6c667f490c9478a659b1e905c4222452c4b96067",
          "md5": "329cdb77d10ba85e59c3b67aa4c8d76b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.2.aar",
          "url": "navigation-runtime-2.4.2.aar",
          "size": 117238,
          "sha512": "f162d61675b6eaeeddf86f8bd7e0fdff49501537be39aa142986f41ad80720f10bdb3b24f8a9b2ddba0948874492876348213cd109748f442d9a147ac53b5ac8",
          "sha256": "ae8a1bce56e5df56e6512103c3d0608edbd1d48cc409649b12f482469eec3fbe",
          "sha1": "6c667f490c9478a659b1e905c4222452c4b96067",
          "md5": "329cdb77d10ba85e59c3b67aa4c8d76b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.4.2-sources.jar",
          "url": "navigation-runtime-2.4.2-sources.jar",
          "size": 47025,
          "sha512": "a6f3f54294e741ede056579c2cf88bfc885356653f8ea4bd82817a774fd1d0192e98095b1b93e3e306df03e1526353ecd7018b3d2b66f5a16ceffdb4552d3c06",
          "sha256": "c98ab4a557d3670af51d348e1c445543360d73f13ff7657e2d6386615522b67a",
          "sha1": "0b407b0d69960fa7a1449c3171124b07a4cd8c59",
          "md5": "566a5c2e401e1ae19983686c024aabff"
        }
      ]
    }
  ]
}
