{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle",
    "version": "7.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-7.1.3.jar",
          "url": "gradle-7.1.3.jar",
          "size": 8626742,
          "sha512": "66f4a38a9603c7410b36ce7767e54d2d90c4004bdaec263e6f1f72b8c2ce2fd5c8338db2e42c2b5b589f69675f63f5b020d6af5e69b0e254ec73004707dfb727",
          "sha256": "4b9673197827a725f7ca3d7c86b91e35ca23969a13ea2d5a0f05ad7d2b337a58",
          "sha1": "4bf9ec77c9ec8738dbe58468a2f07b97c5c3c72b",
          "md5": "b339d8c3364dc496e1135ef642130928"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "7.1.3-7984345"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aaptcompiler",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "crash",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-ddmlib-proto",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-gradle-proto",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-additional-test-output-proto",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-coverage-proto",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-retention-proto",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-result-listener-gradle-proto",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "2.0.0-deprecated-use-gradle-api"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "bundletool",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta09"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-processor",
          "version": {
            "requires": "1.0.0-beta09"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.3.0-rc2"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.8-alpha07"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.flatbuffers",
          "module": "flatbuffers-java",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-metadata",
          "version": {
            "requires": "0.1.0-rc2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-7.1.3.jar",
          "url": "gradle-7.1.3.jar",
          "size": 8626742,
          "sha512": "66f4a38a9603c7410b36ce7767e54d2d90c4004bdaec263e6f1f72b8c2ce2fd5c8338db2e42c2b5b589f69675f63f5b020d6af5e69b0e254ec73004707dfb727",
          "sha256": "4b9673197827a725f7ca3d7c86b91e35ca23969a13ea2d5a0f05ad7d2b337a58",
          "sha1": "4bf9ec77c9ec8738dbe58468a2f07b97c5c3c72b",
          "md5": "b339d8c3364dc496e1135ef642130928"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-7.1.3-javadoc.jar",
          "url": "gradle-7.1.3-javadoc.jar",
          "size": 944244,
          "sha512": "78e53bfea77b887cf45882f417a290f4f163d91b2ce1eeade82bb9766dedfa70e3c8a3f0fe85ac657e4d031f5ca8d3a19a8fd22c1bfc7eb941813d2c716792ae",
          "sha256": "45f388510902992b33704aa3efdd7a18f8c00f6e3308293eabfb4e5067ca7240",
          "sha1": "f2111e90a55ef8c3a8093e13289e07e9e2e8ffb2",
          "md5": "d3959289864034a3b921a111c9a877f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-7.1.3-sources.jar",
          "url": "gradle-7.1.3-sources.jar",
          "size": 2524355,
          "sha512": "80945c293ef88fd315147920d19cb90279dc624bcadf5cc7f165bad5ae09d48520c36a3db9874240972889899bc74a49ee96976b3ef6699fde130007fecb2d1a",
          "sha256": "2ddf93696152a5b3ca16f952edf8eea16894aabf89012dfc427189686514ec44",
          "sha1": "f547ef44a494913ef730ded662c55ec132913aea",
          "md5": "f6184eba73b1febf175a43bcf5a4c230"
        }
      ]
    }
  ]
}
