{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.1.0-beta01.aar",
          "url": "camera-core-1.1.0-beta01.aar",
          "size": 576881,
          "sha512": "b948f2dd78c16e3192a7896607cd95ceaa29ab295984037002afdfea6038ffd999b6e991874154797e29dc74e4fb21ffb0cc87f43b94413a93682512b7e2759b",
          "sha256": "a94c2e68ef5310e382d2a8a19e371743bcc480dc26afc8ae897b1c9264b05ad0",
          "sha1": "23b0843592f21a6a7aea131ee5796f261e14ee0b",
          "md5": "01f628a17f0fd95a89c9a84e7571876d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.1.0-beta01.aar",
          "url": "camera-core-1.1.0-beta01.aar",
          "size": 576881,
          "sha512": "b948f2dd78c16e3192a7896607cd95ceaa29ab295984037002afdfea6038ffd999b6e991874154797e29dc74e4fb21ffb0cc87f43b94413a93682512b7e2759b",
          "sha256": "a94c2e68ef5310e382d2a8a19e371743bcc480dc26afc8ae897b1c9264b05ad0",
          "sha1": "23b0843592f21a6a7aea131ee5796f261e14ee0b",
          "md5": "01f628a17f0fd95a89c9a84e7571876d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-core-1.1.0-beta01-sources.jar",
          "url": "camera-core-1.1.0-beta01-sources.jar",
          "size": 430243,
          "sha512": "fb85452a5495e52ce510dde790a931635d7e4ef4a1572f6729c2c06aa303ac61563105a4157fd1f6d9b0ef2aaa5c75e18203708b1ef91e3e2d5799b2402ab17e",
          "sha256": "b0cfafbe944d7c1dc5ad2eb0b36b0aa1e986b1209e042c2d6effd0d13b5a3974",
          "sha1": "677515668e1467011a1ffcacc5433740009a2699",
          "md5": "04997c288cdd57520e6025d2e3d32b44"
        }
      ]
    }
  ]
}
