{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.4.2.aar",
          "url": "navigation-common-2.4.2.aar",
          "size": 155345,
          "sha512": "84d8f90fc4a5d646379f79854ffb3ee7df26610a284601203e038e07eba4001a19e310aa91540bb790ffe68ebea21aa6089b624463a934e0c69b1e23798ef1cc",
          "sha256": "c6874a382402073a3eff863e5012b18a6b7c8c3f4b135c18e60a16239a532854",
          "sha1": "a6c52c1c40f6a1a223b271c1802d056e870732c8",
          "md5": "be04ddef72f3d94308584d612c08960e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.4.2.aar",
          "url": "navigation-common-2.4.2.aar",
          "size": 155345,
          "sha512": "84d8f90fc4a5d646379f79854ffb3ee7df26610a284601203e038e07eba4001a19e310aa91540bb790ffe68ebea21aa6089b624463a934e0c69b1e23798ef1cc",
          "sha256": "c6874a382402073a3eff863e5012b18a6b7c8c3f4b135c18e60a16239a532854",
          "sha1": "a6c52c1c40f6a1a223b271c1802d056e870732c8",
          "md5": "be04ddef72f3d94308584d612c08960e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-2.4.2-sources.jar",
          "url": "navigation-common-2.4.2-sources.jar",
          "size": 54365,
          "sha512": "c9a8927a0b7a90819dc8064d1b4ac498508d29e665dbd4774450ead21d097d75605d02740db8e25ecd52881f85bc545ea99b45c6b80565b570e4d188e3f7973a",
          "sha256": "2557fa3c90b4ee1b6deb5701c6af7d954b73a283c39797f0ccba2e1549fbf6ce",
          "sha1": "fe252ed1ac77d54a612a390ad673106111bec381",
          "md5": "1178c942a4d631e43cdd6cfb3143a733"
        }
      ]
    }
  ]
}
