{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "7.1.3-7984345",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aapt2-proto-7.1.3-7984345.jar",
          "url": "aapt2-proto-7.1.3-7984345.jar",
          "size": 747666,
          "sha512": "2cb2faec3a156314000b390a0061c602025a092ec5fce3544d05cd65a57ce6249e40725d342ebf5b4ef070287db0f89273f3eecb8df0e3c368082c3dc240ded0",
          "sha256": "75d9adddbaedf7484c6bdbffad8058fa8bdca5efb83c189ad5e2891c6a13793c",
          "sha1": "a284d9f31796eb79b2131da9fe4e041035514693",
          "md5": "3b20127df728f35beff95211fd6a0b5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-7.1.3-7984345.jar",
          "url": "aapt2-proto-7.1.3-7984345.jar",
          "size": 747666,
          "sha512": "2cb2faec3a156314000b390a0061c602025a092ec5fce3544d05cd65a57ce6249e40725d342ebf5b4ef070287db0f89273f3eecb8df0e3c368082c3dc240ded0",
          "sha256": "75d9adddbaedf7484c6bdbffad8058fa8bdca5efb83c189ad5e2891c6a13793c",
          "sha1": "a284d9f31796eb79b2131da9fe4e041035514693",
          "md5": "3b20127df728f35beff95211fd6a0b5c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-7.1.3-7984345-javadoc.jar",
          "url": "aapt2-proto-7.1.3-7984345-javadoc.jar",
          "size": 1433080,
          "sha512": "6bd8b7fbdb07e91c810df96c43376c314938eba42251a5874b12bb5baf9b15334682828aa82646ff4e8fd98c2d15983400b1dbde159bdd25048d9cc01668e9a2",
          "sha256": "96e81830130301ba881fb41bd8cc1a650844e97982eea2877d2e1d4630b3f26f",
          "sha1": "41bbde2e1c9db7b3b6ed7c46c734448590498691",
          "md5": "c1fb1bd2adfe79837fcc9744d507ff66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-7.1.3-7984345-sources.jar",
          "url": "aapt2-proto-7.1.3-7984345-sources.jar",
          "size": 200643,
          "sha512": "bd765e9e8f300d6544cbb776ab80b8e343c62709c9912509999c38d27317f4a0a353b116dc428988a8fdc5e7ffbbf9f653bb1bfbadc1b3b46f039f7c68449c38",
          "sha256": "2a673e88fb097cd480d74da846de529a62a79545234dc2eedd6c20aa05c51fa4",
          "sha1": "0088bb56504b7d327bf2028ad6385d4373a93bd5",
          "md5": "6cd448165509c66b6cc1b0c7e104058b"
        }
      ]
    }
  ]
}
